framework: golang
version: 1.0.0
preRun:
  command:
    - "go get -v -t -d ./..."  
    - "go get golang.org/x/sys@v0.0.0-20180926160741-c2ed4eda69e7"
    - "go mod tidy"
    - "go mod vendor"
postMerge:
  pattern:
    - "./**/*_test.go"
